object Versions {
    const val roomVersion = "2.5.2"
    const val viewModelKTXVersion = "2.6.2"
    const val coroutinesVersion = "1.7.2"
    const val navVersion = "2.6.0"
    const val hiltVersion = "2.47"
    const val coreKTXVersion = "1.10.1"
    const val lifecycleRuntimeKTXVersion = "2.6.2"
    const val activityComposeVersion = "1.7.2"
    const val composeBomVersion = "2023.03.00"
    const val jUnitVersion = "4.13.2"
    const val androidJUnitVersion = "1.1.5"
    const val espressoVersion = "3.5.1"
    const val hiltNavVersion = "1.0.0"
    const val retrofitVersion = "2.9.0"
    const val okHttpVersion = "4.11.0"
    const val pagingVersion = "3.2.1"
    const val coilVersion = "2.4.0"
    const val materialIconsVersion = "1.4.2"
    const val accomnpanistVersion = "0.30.1"
    const val dataStoreVersion =  "1.0.0"
}